### ISSUE TITLE
ezANOVA: Automatically check assumptions

### ISSUE THREAD

**Issue by ghost** [mike-lawrence/ez#57]
I wonder if it is possible to automatically check all assumptions when running ezANOVA (especially for mixed ANOVA for example as described here https://statistics.laerd.com/spss-tutorials/mixed-anova-using-spss-statistics.php).

As far as I know, Levene's and Mauchly's are already included (Levene's test does not seem to run when a "within" parameter is specified), but normality and maybe outliers could also be checked automatically. The cherry on top would be a command for all relevant plots (Q-Q plot, distribution of residuals etc.) as is available in R calling `plot` on a linear model.

**Comment by mike-lawrence** [comment]
Thanks for your suggestion, but at this point I'm not accepting feature requests for `ez`. It was developed early in my career and I've since changed both my philosophy and practice of statistics sufficiently that I have moral concerns in contributing to the continued use of the blunt and often ill-suited tool that is ANOVA. Folks are of course free to fork and/or submit pull requests that implement new features.

**Comment by ghost** [comment]
Thank you for your honest response. Would you be open to elaborate on why you consider ANOVA often to be ill-suited?
